-- 0005 — programs.website_url (additive, nullable).
-- Generated by drizzle-kit. The generator also emitted a DROP/CREATE of
-- "workspace_invites_pending_key": that was snapshot drift only (0000's
-- snapshot predates 0002, which already rebuilt the index on lower(email)), so
-- it was removed here; 0005_snapshot.json now matches the live index.
-- No RLS change: policies are row-scoped, and `authenticated` already holds
-- table-level SELECT/INSERT/UPDATE on programs (0001), which covers new columns.
ALTER TABLE "programs" ADD COLUMN "website_url" text;
